site_name: Poscidyn
site_description: Python Oscillator Dynamics
repo_url: https://github.com/rknetemann/poscidyn
repo_name: rknetemann/poscidyn

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            show_signature: true
            signature_crossrefs: true
            docstring_style: google
            merge_init_into_class: true

nav:
  - Poscidyn in a nutshell: poscidyn-in-a-nutshell.md

  - Getting started: getting-started.md

  - Usage: 
    - Basic usage: usage/basic_usage.md
    - Extending Poscidyn: usage/extending_poscidyn.md

  - API Reference:
      - Overview: api/index.md
      - Methods: 
        - time_response: api/time_response.md
        - frequency_sweep: api/frequency_sweep.md
      - Classes:
        - Oscillator models: usage/oscillator_models.md
        - Excitation models: usage/excitation.md
        - Solvers: usage/solvers.md
        - Multistart strategies: usage/multistart_strategies.md
        - Frequency sweep methods: usage/frequency_sweep_strategies.md
        - Results analysis: usage/results_analysis.md

  - Simulation examples: 
    - Time Response: 
      - Duffing oscillator: examples/time_response/duffing_oscillator.md
      - MDOF oscillator: examples/time_response/mdof_oscillator.md
    - Frequency Sweep: 
      - Duffing oscillator: examples/frequency_sweep/duffing_oscillator.md
      - MDOF oscillator: examples/frequency_sweep/mdof_oscillator.md
