site_name: Poscidyn
site_description: Python Oscillator Dynamics
site_url: https://rknetemann.github.io/poscidyn/
repo_url: https://github.com/rknetemann/poscidyn
repo_name: rknetemann/poscidyn

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            show_signature: true
            signature_crossrefs: true
            docstring_style: google
            merge_init_into_class: true

nav:
  - Poscidyn in a nutshell: index.md

  - For who is Poscidyn?: for-who-is-poscidyn.md

  - Where Poscidyn shines: where-poscidyn-shines.md

  - Getting started: 
    - Installation: getting-started/installation.md
    - Understanding Poscidyn: getting-started/understanding-poscidyn.md
    - Limitations: getting-started/limitations.md
    - Next steps: getting-started/next-steps.md

  - Usage: 
    - Basic usage: 
      - Setting up an oscillator model: usage/basic-usage/oscillator-models.md
      - Setting up an excitation model: usage/basic-usage/excitation-models.md
      - Performing a time response: usage/basic-usage/time-response.md
      - Performing a frequency sweep: usage/basic-usage/frequency-sweep.md
    - Advanced usage:
      - Choosing a solver: usage/advanced-usage/choosing-a-solver.md
      - Configuring multistart strategies: usage/advanced-usage/configuring-multistart-strategies.md
      - Configuring sweep methods: usage/advanced-usage/configuring-sweep-methods.md
    - Extending Poscidyn: usage/extending-poscidyn.md

  - Examples: 
    - Overview: examples/overview.md
    - Time Response: 
      - Duffing oscillator: examples/time-response/duffing-oscillator.md
      - MDOF oscillator: examples/time-response/mdof-oscillator.md
    - Frequency Sweep: 
      - Duffing oscillator: examples/frequency-sweep/duffing-oscillator.md
      - MDOF oscillator: examples/frequency-sweep/mdof-oscillator.md

  - API Reference:
      - Methods: 
        - time_response: api/methods.md#time-response
        - frequency_sweep: api/methods.md#frequency-sweep
      - Classes:
        - Oscillator models: api/classes.md#oscillator-models
        - Excitation models: api/classes.md#excitation-models
        - Solvers: api/classes.md#solvers
        - Multistart strategies: api/classes.md#multistart-strategies
        - Frequency sweep methods: api/classes.md#frequency-sweep-strategies
        - Results analysis: api/classes.md#results-analysis